// prototype 1 MAIN LINE

// By Simon Mitchell					96878291

// 27/3/98

// Main line for PROTOTYPE 1, Object Orientated version (NON GUI)
// of part A of the "biomorphs" project.

#include<iostream.h>
#include"selectmn.h"

// Create the natural selection manager (essentially the object manager)

selectionManager myManager;

//-------------------------------
// MAIN LINE
//-------------------------------

void main () {myManager.run();}
